Section "InputClass"
    Identifier "MUAG libinput"
    MatchIsPointer "on"
    Driver "libinput"
    Option "AccelProfile" "adaptive"
EndSection

Section "InputClass"
    Identifier "MUAG touchscreen"
    MatchIsTouchscreen "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
EndSection

Section "InputClass"
    Identifier "MUAG keyboard"
    MatchIsKeyboard "on"
    Driver "libinput"
EndSection
